---
- name: Cria usuário
  oracle.oci.oci_identity_user:
    name: "{{ item }}"
    description: "Membro do grupo {{ group_name }}"
    compartment_id: "{{ parent_compartment_ocid }}"
    email: "{{ item }}{{ dominio }}"
  register: criacaousuario
- set_fact:
    user_ocid: "{{ criacaousuario.user['id'] }}"
- debug:
    msg: "Usuário {{ item }} criado"
  when: criacaousuario.changed

- name: Adiciona usuário ao grupo
  oracle.oci.oci_identity_user_group_membership:
    user_id: "{{ user_ocid }}"
    group_id: "{{ group_ocid }}"
    compartment_id: "{{ parent_compartment_ocid }}"
  register: result
- set_fact:
    user_group_membership_ocid: "{{ result.user_group_membership['id'] }}"
 
- name: Cria senha do usuário
  oracle.oci.oci_identity_ui_password:
    user_id: "{{ user_ocid }}"
  register: result
  when: criacaousuario.changed
- set_fact:
    user_password: "{{ result.ui_password['password'] }}"
  when: criacaousuario.changed
- debug:
    msg: "Senha de {{ item }} é {{ user_password }}"
  when: criacaousuario.changed


- name: Send mail
  community.general.sendgrid:
    api_key: "{{ API_SENDGRID_KEY }}"
    from_address: "{{EMAIL_SENDER}}"
    to_addresses:
      - "{{ item }}{{ dominio }}"
    subject: "Usuário criado com sucesso."
    body: "Seu usuário foi criado. Seu login é {{ item }} e senha : {{ user_password }}."
  delegate_to: localhost

