---

- name: Create group
  oracle.oci.oci_identity_group:
    compartment_id: "{{ parent_compartment_ocid }}"
    description: "Gerenciar os recursos da compute"
    name: "{{ compute_group_name }}"

- name: Create group
  oracle.oci.oci_identity_group:
    compartment_id: "{{ parent_compartment_ocid }}"
    description: "Gerenciar os recursos da Rede"
    name: "{{ redes_group_name }}"

- name: Create group
  oracle.oci.oci_identity_group:
    compartment_id: "{{ parent_compartment_ocid }}"
    description: "Gerenciar os recursos do DBA"
    name: "{{ dba_group_name }}"

- name: Create group
  oracle.oci.oci_identity_group:
    compartment_id: "{{ parent_compartment_ocid }}"
    description: "Gerenciar os recursos do CloudAdmin"
    name: "{{ cloudadm_group_name }}"

- name: Create group
  oracle.oci.oci_identity_group:
    compartment_id: "{{ parent_compartment_ocid }}"
    description: "Gerenciar os recursos dos Operadores"
    name: "{{ operadores_group_name }}"

